### ISSUE TITLE
Why are we the only people needing this?

### ISSUE THREAD

**Issue by ken107** [smujmaiku/jest-expect-json#1]
Am I missing something?  Is there another way to do this?  What are people doing when they need to match JSON strings?  Are they doing `expect.toBe(JSON.stringify(myExpection))`?  Cuz that's not reliable

**Comment by smujmaiku** [comment]
I've certainly replaced a number of my tests just like that. The readme very much contains real life examples in this case. Thank you for letting me know other people like yourself are finding this package useful. Let me know if you think there are any improvements I could make.

**Comment by rhwinter** [comment]
@ken107 I'm also very curious about this.

Are folks not testing their code properly?...

**Comment by smujmaiku** [comment]
The team I work on currently prefers to use snapshots for many things even on mocked functions a la `expect(dispatch.mock.calls).toMatchSnapshot()`. I don't prefer snapshots as I find them very disconnected from the test but it's not a hill worth dying on. I still use this on personal projects and it lives on with previous teams.

Still, I'm pleased you two have found this package interesting. Thank you for having a look at it
